services:
  # ── Servicio Frontend  ────────────────
  frontend:
    build: .
    container_name: proyecto_frontend
    restart: unless-stopped

    # ── Variables de entorno ───────────────────────────────────
    environment:
      PORT: 5000
      DEBUG: "False"

      # URL interna del backend dentro de Docker
      BACKEND_URL: http://proyecto_backend:3000

    # ── Exposición al navegador ────────────────────────────────
    ports:
      - "80:5000"

    # ── Red compartida con backend ─────────────────────────────
    networks:
      - innovatech-net

# ── Red externa compartida ─────────────────────────────────────
networks:
  innovatech-net:
    external: true
