name: Build y Deploy Frontend (Docker + EC2)

on:
  push:
    branches:
      - deploy

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build y push de la imagen
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend-eval2:latest

      - name: Deploy en EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            echo "Descargando imagen actualizada..."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/frontend-eval2:latest

            echo "Deteniendo contenedor anterior..."
            docker stop proyecto_frontend || true
            docker rm proyecto_frontend || true

            echo "Levantando nuevo contenedor..."
            docker run -d \
              --name proyecto_frontend \
              -p 5000:5000 \
              --restart always \
              -e PORT=5000 \
              -e DEBUG=False \
              -e BACKEND_URL=http://${{ secrets.EC2_BACKEND_PRIVATE_IP }}:3000 \
              -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
              ${{ secrets.DOCKERHUB_USERNAME }}/frontend-eval2:latest

            echo "Deploy frontend completado"


            
